export enum ChannelType {
  WHATSAPP = 'WHATSAPP',
  TELEGRAM = 'TELEGRAM',
  SIGNAL = 'SIGNAL',
  IMESSAGE = 'IMESSAGE',
  SMS = 'SMS',
  PHONE = 'PHONE',
  EMAIL = 'EMAIL',
  INSTAGRAM = 'INSTAGRAM',
  MESSENGER = 'MESSENGER',
  OTHER = 'OTHER',
}
